# Spring Boot
spring.application.name=mongo-rabbit-bridge
# disable any embedded web server
spring.main.web-application-type=none

# MongoDB
spring.data.mongodb.uri=mongodb://appointments-db:27017/gestmed_appointments_db?replicaSet=rs0

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Logging
logging.level.org.springframework.data.mongodb.core.messaging=DEBUG

# Bridge settings
app.bridge.email-queue=email-queue
app.bridge.sms-queue=sms-queue
app.bridge.appointment-collection=appointments

# Downstream service base URL
app.bridge.service-api-base-url=http://api-gateway:3000/api

# enable debug logging in our listener package
logging.level.com.rabbit.bridge.mongorabbitbridge.listener=DEBUG
