spring.application.name=mongo-rabbit-bridge

spring.data.mongodb.uri = mongodb://appointments-db:27017/gestmed_appointments_db?replicaSet=rs0
spring.rabbitmq.host = localhost
spring.rabbitmq.port = 5672
spring.rabbitmq.username = guest
spring.rabbitmq.password = guest

logging.level.org.springframework.data.mongodb.core.messaging=DEBUG

# application.properties (defaults)
app.bridge.emailCollection=email
app.bridge.smsCollection=sms
app.bridge.emailQueue=email-queue
app.bridge.smsQueue=sms-queue
app.bridge.appointment-collection=appointments